services:
  mariadb:
    platform: linux/x86_64
    container_name: container-mariadb
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
    ports:
      - '3306:3306'
    volumes:
      - mariadb-data:/var/lib/mysql

  adminer:
    container_name: container-adminer
    restart: always
    image: adminer:latest
    ports:
      - '3001:8080'
    depends_on:
      - mariadb
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

volumes:
  mariadb-data:
