import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/lib/providers/providers';
import { Navbar } from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Trip Planner',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="en">
    <body>
      <Providers>
        <Navbar />
        {children}
      </Providers>
    </body>
  </html>
);

export default RootLayout;
