import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/lib/providers/providers';
import { Navbar } from '@/components/Navbar/Navbar';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: 'Trip Planner',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <ClerkProvider>
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  </ClerkProvider>
);

export default RootLayout;
